coverage:
  status:
    project:
      default:
        target: 50%
        threshold: 25%
        paths:
          - sfdata_cincensus
    patch:
      default:
        target: 50%
        threshold: 25%
        paths:
          - sfdata_cincensus